baseURL = "https://blog.mattdiflorio.com/"
languageCode = "en-us"
title = "Madhava Di Florio"
theme = "hyde"

[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/mierz00/"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/matt-diflorio/"}
  ]

[params]
  description = "Software developer"
